#!/usr/bin/with-contenv bash


echo "starting rtorrent"
su - mediadepot -c "screen -dmfa -S rtorrent /usr/local/bin/rtorrent -n -o import=/srv/rtorrent/config/rtorrent.rc"



until [[ ( -e "/srv/rtorrent/data/session/rtorrent.lock" ) && ( -e "/srv/rtorrent/data/rtorrent.log" ) ]];
do
sleep 1s
done

echo "rtorrent started. checking xmlrpc connection.."
python xmlrpc2scgi.py -p scgi://127.0.0.1:5000 system.hostname

echo "xmlrpc port accessible on 127.0.0.1:5000"


# sleep now, rtorrent is running as a detached process, logs are redirected to STDOUT.
#while :; do sleep 2073600; done


#rtorrent_pid=$(< /srv/rtorrent/data/session/rtorrent.lock | cut -d '+' -f 2)
tail -n 1 -f /srv/rtorrent/data/rtorrent.log