#!/usr/bin/with-contenv bash

# make folders (Original)
mkdir -p \
	/srv/rtorrent/data/flood/db/ \
	/srv/rtorrent/data/session/

# make folders
mkdir -p \
	/config{/log/nginx,/log/rtorrent,/log/rutorrent,/nginx,/nginx/conf.d,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users,/.irssi,/flood} \


[[ ! -e /srv/rtorrent/config/rtorrent.rc ]] && \
	cp /defaults/rtorrent.rc /srv/rtorrent/config/rtorrent.rc


# delete lock file if exists
[[ -e /srv/rtorrent/data/session/rtorrent.lock ]] && \
	rm /srv/rtorrent/data/session/rtorrent.lock


# copy config files/set links etc...
[[ ! -f /srv/rtorrent/app/flood/config.js ]] && \
	cp /defaults/config.js /srv/rtorrent/app/flood/config.js



# permissions
chown mediadepot:mediadepot -R /srv/rtorrent/data/
chown mediadepot:mediadepot -R /srv/rtorrent/config/
