#!/usr/bin/with-contenv bash

# make folders
mkdir -p /config/tmp /detach_sess

# copy config files/set links etc...
[[ ! -f /usr/flood/config.js ]] && cp /defaults/config.js /usr/flood/config.js

# set perms
chown abc:abc -R /config /detach_sess
chown abc:abc -R /usr/share/webapps/rutorrent
chown abc:abc /downloads
chmod 755 /usr/local/bin/curl
